### ISSUE TITLE
Error Message On k3s cluster Creation

### ISSUE THREAD

**Issue by ssmiller25** [civo/cli#17]
Received the following error message.  This happend around 14:48 UTC.  Cluster creation started around 14:40.  The cluster did eventually come up.  I'll leave cluster up over the weekend if that would be helpful.

```text
Creating k8s-intro
Creating a 3 node k3s cluster of g2.small instances called k8s-intro... / panic: interface conversion: error is *url.Error, not civogo.HTTPError

goroutine 1 [running]:
github.com/civo/civogo.decodeERROR(0xad0e40, 0xc00015f920, 0x17, 0x0)
	/home/runner/go/pkg/mod/github.com/civo/civogo@v0.2.15/errors.go:279 +0x11580
github.com/civo/civogo.(*Client).ListKubernetesClusters(0xc000033200, 0x24, 0xc000408180, 0x24)
	/home/runner/go/pkg/mod/github.com/civo/civogo@v0.2.15/kubernetes.go:128 +0x1fd
github.com/civo/civogo.(*Client).FindKubernetesCluster(0xc000033200, 0xc000408180, 0x24, 0xc0001f5a38, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/civo/civogo@v0.2.15/kubernetes.go:141 +0x43
github.com/civo/cli/cmd.glob..func41(0xe84e40, 0xc0000756e0, 0x1, 0x6)
	/home/runner/work/cli/cli/cmd/kubernetes_create.go:99 +0x4eb
github.com/spf13/cobra.(*Command).execute(0xe84e40, 0xc000075680, 0x6, 0x6, 0xe84e40, 0xc000075680)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xe88800, 0x43b8aa, 0xe477c0, 0xc000054750)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/civo/cli/cmd.Execute()
	/home/runner/work/cli/cli/cmd/root.go:26 +0x31
main.main()
	/home/runner/work/cli/cli/main.go:23 +0x20
make: *** [Makefile:41: kubeconfig.k8s-intro] Error 2
```

**Comment by alejandrojnm** [comment]
Hi @ssmiller25, I will check this error, did you try to reproduce the error or was the error one time only?

**Comment by ssmiller25** [comment]
I was unable to recreate the error this morning.  Although I should have highlighted the `interface conversion: error is *url.Error, not civogo.HTTPError` section of the errro, which leads me to believe that an error is being returned as the wrong struct somewhere.

I forgot to also include the command I used when this error was generated.  It's below:

```sh
civo k3s create k8s-intro -n 3 --size g2.small --wait
```
