### ISSUE TITLE
Civo apikey add yields Go nil assignment panic on Ubuntu 20.04 Focal Release on Docker

### ISSUE THREAD

**Issue by HimikoTachibana** [civo/cli#3]
Repo steps:

1. Install Ubuntu 20.04 Focal Release as guest OS on host OS Windows 10.
2. Install Docker per official instructions docker version at time of writing is 19.03.11
3. Follow "Docker Usage" steps as instructed per Read Me put the civo alias in ~./bashrc file
4. Attempt to add an API key as instructed in API Keys section of Read Me

Performing the above steps yields the following stack trace:

```
civo apikey add Demo <api key>
EOF
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/civo/cli/cmd.glob..func4(0xd6a2e0, 0xc00000cdc0, 0x2, 0x2)
	/home/runner/work/cli/cli/cmd/apikey_save.go:17 +0x8b
github.com/spf13/cobra.(*Command).execute(0xd6a2e0, 0xc00000cd80, 0x2, 0x2, 0xd6a2e0, 0xc00000cd80)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xd65180, 0x43b4da, 0xd26be0, 0xc00002c750)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/civo/cli/cmd.Execute()
	/home/runner/work/cli/cli/cmd/root.go:26 +0x31
main.main()
	/home/runner/work/cli/cli/main.go:23 +0x20
```

**Comment by alejandrojnm** [comment]
I fix this in the last release [v0.6.2](https://github.com/civo/cli/releases/tag/v0.6.2), can you tested?
